version: '3.7'
services:
  frontend:
    container_name: blog-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  backend:
    container_name: blog-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3095:3095
    depends_on:
      - postgres
    env_file:
      - ./backend/.env

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: db
